add is active
secit-pl/imap-bundle pull request #41
Opened 2024-03-18 19:25 UTC by antedebaas

I need a flag to check if a config is enabled.

2024-03-20 09:33 UTC, secit-pl commented
Please update the documentation before merge.

2024-03-21 18:47 UTC, antedebaas commented
there you go.
renamed it to enabled so the column matches the config

2024-04-15 20:26 UTC, antedebaas commented
@secit-pl friendly ping

2024-04-16 01:26 UTC, secit-pl requested changes
You won't like me :) Please see my comments. Most of them are related to the coding standard.

2024-04-16 01:26 UTC, secit-pl commented on Command/ValidateConnectionsCommand.php
> +        {
Please place opening curly bracket in the same line as if (see Symfony Coding Standard https://symfony.com/doc/current/contributing/code/standards.html#symfony-coding-standards-in-detail)

plus space after "if"

2024-04-16 01:26 UTC, secit-pl commented on Connection/Connection.php
> +        }
Please add new line after closing curly bracket (see: Symfony Coding Standard https://symfony.com/doc/current/contributing/code/standards.html#symfony-coding-standards-in-detail)

2024-04-16 01:26 UTC, secit-pl commented on Connection/Connection.php
> +        }
Please add new line after closing curly bracket (see: Symfony Coding Standard https://symfony.com/doc/current/contributing/code/standards.html#symfony-coding-standards-in-detail)

2024-04-16 01:26 UTC, secit-pl commented on Connection/Connection.php
> +        if(!$this->isEnabled()) {
Please add space between if and "(" (see: Symfony Coding Standard https://symfony.com/doc/current/contributing/code/standards.html#symfony-coding-standards-in-detail)

2024-04-16 01:26 UTC, secit-pl commented on Command/ValidateConnectionsCommand.php
> +        if($connection->isEnabled())
Please add space between if and "(" (see: Symfony Coding Standard https://symfony.com/doc/current/contributing/code/standards.html#symfony-coding-standards-in-detail)

2024-04-16 01:26 UTC, secit-pl commented on Connection/Connection.php
> +                $this->enabled,
As I can see the 6th argument of the [Mailbox::__construct()](https://github.com/barbushin/php-imap/blob/94107fdd1383285459a7f6c2dd2f39e25a1b8373/src/PhpImap/Mailbox.php#L168) is  $trimImapPath, why are you passing enabled to it?

2024-04-16 01:26 UTC, secit-pl commented on Connection/Connection.php
> +        if(!$this->isEnabled()) {
Please add space between if and "(" (see: Symfony Coding Standard https://symfony.com/doc/current/contributing/code/standards.html#symfony-coding-standards-in-detail)

2024-04-16 01:26 UTC, secit-pl commented on Connection/Connection.php
> +            throw new ConnectionException(array('Mailbox is not enabled'));
testConnection should always return true or false and should not throw error in any case. You should return false here.

2024-04-16 01:26 UTC, secit-pl commented on Connection/Connection.php
> +            throw new ConnectionException(array('Mailbox is not enabled'));
I do not thin that we should thow here ConnectionException as it indicates that the problem is in PhpImap library, not in the bundle. I think we should thow here ErrorException. Additionally please do not use array() notation, please use [] instead.

2024-04-16 01:26 UTC, secit-pl commented on Command/ValidateConnectionsCommand.php
> +            $enabled = "<info>YES</info>";
Please use ' instead of "

2024-04-16 01:26 UTC, secit-pl commented on Command/ValidateConnectionsCommand.php
> +            $enabled = "<error>NO</error>";
Please use ' instead of "

2024-04-16 01:26 UTC, secit-pl commented on DependencyInjection/Configuration.php
> +                            ->scalarNode('enabled')
Lease add default value as in create_attachments_dir_if_not_exists: "->defaultTrue()".

2024-04-16 10:55 UTC, secit-pl commented
Changes looks ok. One thought before merge, shouldn't there go some logic behind the isEnabled()? At this moment the flag doesn't do anything. Maybe we should block possibility to get the mailbox (getMailbox() -> if (!$connection->isEnabled()) throw \ErrorException('connection disabled')) and do not initiate connection on the test command for disabled connections? WDYT?

2024-04-16 15:00 UTC, antedebaas commented
I agree;
I added code for it.
i also modified the validate-connection command not to try and open the mailbox when its disabled

2024-04-16 18:21 UTC, secit-pl approved these changes

2024-04-16 18:22 UTC, merged

2024-04-16 18:23 UTC, secit-pl commented
Merged. Thank you for your contribution!